version: '3'
services:
  pystro:
    build: .
    ports:
      - "8888:8000"
    env_file: .env
    restart: always
    links:
      - mysql:dbserver

  mysql:
    image: mysql
    restart: always
    env_file: .env    
    expose:
      - '3306'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'pass'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysql      
    